# Generated by Django 5.0.4 on 2024-04-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0002_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
