# Generated by Django 5.0.4 on 2024-04-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0006_remove_resume_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
