# Generated by Django 5.0.4 on 2024-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0007_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
            ],
        ),
    ]
