# Generated by Django 5.0.4 on 2024-04-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0008_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
