# Generated by Django 5.0.4 on 2024-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0014_remove_resumetemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
