# Generated by Django 5.0.4 on 2024-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0015_resumetemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('skill4', models.CharField(max_length=100)),
                ('skill5', models.CharField(max_length=100)),
                ('degree1', models.CharField(max_length=100)),
                ('college1', models.CharField(max_length=100)),
                ('year1', models.IntegerField()),
                ('degree2', models.CharField(max_length=100)),
                ('college2', models.CharField(max_length=100)),
                ('year2', models.IntegerField()),
                ('college3', models.CharField(max_length=100)),
                ('year3', models.IntegerField()),
                ('degree3', models.CharField(max_length=100)),
                ('lang1', models.CharField(max_length=50)),
                ('lang2', models.CharField(max_length=50)),
                ('lang3', models.CharField(max_length=50)),
                ('project1', models.CharField(max_length=100)),
                ('durat1', models.CharField(max_length=50)),
                ('desc1', models.TextField()),
                ('project2', models.CharField(max_length=100)),
                ('durat2', models.CharField(max_length=50)),
                ('desc2', models.TextField()),
                ('company1', models.CharField(max_length=100)),
                ('post1', models.CharField(max_length=100)),
                ('duration1', models.CharField(max_length=50)),
                ('lin11', models.CharField(max_length=200)),
                ('company2', models.CharField(max_length=100)),
                ('post2', models.CharField(max_length=100)),
                ('duration2', models.CharField(max_length=50)),
                ('lin21', models.CharField(max_length=200)),
                ('ach1', models.CharField(max_length=100)),
                ('ach2', models.CharField(max_length=100)),
                ('ach3', models.CharField(max_length=100)),
            ],
        ),
    ]
