# Generated by Django 5.0.4 on 2024-04-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0016_resumeform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeForm',
        ),
    ]
