# Generated by Django 5.0.4 on 2024-04-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0018_contactmessage_delete_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactForm',
        ),
    ]
