# Generated by Django 5.0.4 on 2024-04-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0020_contactenquiry_delete_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactEnquiry',
        ),
    ]
